### ISSUE TITLE
bug: showPercentage is flipped

### ISSUE THREAD

**Issue by samoojj** [AdamVig/battery-indicator-element#159]
The ternary in the `buildTitle` function is flipped.

The attribute `showPercentage` defaults to false, which should hide the percentage from the title. However, the ternary includes the percentage in the false case.

To fix this, the two cases should be swapped.

https://github.com/AdamVig/battery-indicator-element/blob/7594e48ee284fbbe011dc3cb09245f8373defcc3/src/battery-indicator.ts#L42

**Comment by AdamVig** [comment]
Fixed in `battery-indicator-element@1.1.6`.
